name: SkyBlockInVanilla
version: 1.0.0
main: misc.Plugin
api-version: '1.20.5'

commands:
  getopitems:
    description: Get insanely overpowered SkyBlock items!  Valid itemSets - combat, ingredient, summon
    usage: /getopitems [itemSet] <player>
  w:
    description: Whisper messages to another player!
    usage: /w [player] [message]