name: SkyBlockInVanilla
version: 1.0.0
main: misc.Plugin
api-version: '1.20'

commands:
  getopitems:
    description: Get insanely overpowered SkyBlock items!
    usage: /getopitems [itemSet] <player>
  smite:
    description: Summons lightning on a player.  Electrifying!
    usage: /smite [player]
  getopeffects:
    description: Get insanely overpowered Potion Effects!
    usage: /getopeffects [clearEffects] <player>
  w:
    description: Whisper messages to another player!
    usage: /w [player] [message]
  donothing:
    description: Does Nothing
    usage: /donothing
  god:
    description: Act like you are GOD!
    usage: /god [message]