name: Manual wiki sync
on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Wiki Sync
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/wiki-sync.yml/dispatches \
            -d '{"ref":"autowiki"}'
